spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tmac?characterEncoding=utf-8
    username: root
    password: ENC@[sZbBNG0YNJaPUYpOzj2s6JYFu0EHBXQc]
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

application:
  cors:
    allowed-origins: http://localhost:4200,http://localhost:4201
  web:
    upload-path: E:\resources\static