spring:
  datasource:
    url: jdbc:mysql://rm-bp1945qyl1cv927y1ao.mysql.rds.aliyuncs.com:3306/tmac?characterEncoding=utf-8
    username: root
#    password: mhl123123
    password: ENC@[jQmQIXjiz8q/IXsXqhOG2HKYiq+F0iAq]
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

application:
  cors:
    allowed-origins: http://112.74.54.193,http://112.74.54.193:4200,http://112.74.54.193:4201,http://localhost:4200
  web:
    upload-path: /usr/tmac/static