spring:
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  messages:
    basename: ValidationMessages
    encoding: UTF-8
    elasticsearch:
      jest:
        uris: http://localhost:9200/
        read-timeout: 20000 #读取超时
        connection-timeout: 20000 #连接超时
#    hibernate:
#      ddl-auto: update
  profiles:
#    active: dev
    active: local
flyway:
  baseline-on-migrate: true
  locations: db/migration,db/migration-mock

server:
  servlet-path: /api
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: secretkey
    property:
      prefix: "ENC@["
      suffix: "]"

